WIP/Sources/WingS/WingS/WingS/Models/DTOs/CreateOrganization.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WingS.Models.DTOs
{
    public class CreateOrganization
    {
        public string OrganizationName { get; set; }
        [AllowHtml]
        public string Introduction { get; set; }
        public string LogoUrl { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
    }
}

WIP/Sources/WingS/WingS/WingS/Models/Organization.cs
namespace WingS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public class Organization
    {
        [Key]
        [ForeignKey("Ws_User")]
        public int OrganizationId { get; set; }
        public string OrganizationName { get; set; }
        public string EOrganizationName { get; set; }
        public string Introduction { get; set; }
        public string LogoUrl { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public bool IsVerify { get; set; }
        public int Point { get; set; }
        public DateTime CreatedDate { get; set; } 
        public virtual ICollection<Event> Events { get; set; }
        public virtual Ws_User Ws_User { get; set; }
    }
}

WIP/Sources/WingS/WingS/WingS/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WingS.DataAccess;
using WingS.DataHelper;
using WingS.Models;
using WingS.Models.DTOs;

namespace WingS.Controllers
{
    public class OrganizationController : Controller
    {
        public ActionResult CreateOrganization(CreateOrganization organization, HttpPostedFileBase LogoImage)
        {
            //Models.Organization newOrganization;
            try
            {
                string logoName = WsConstant.randomString() + Path.GetExtension(LogoImage.FileName).ToLower();
                string path = Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Content/Upload"), logoName);
                LogoImage.SaveAs(path);
                organization.LogoUrl = "/Content/Upload/" + logoName;

                using (var db = new OrganizationDAL())
                {
                    db.AddNewOrganization(organization, User.Identity.Name);
                }
            }
            catch (Exception)
            {
                return Redirect("/#/Error");
            }

            return Redirect("/#/Home");
        }

        public ActionResult EditOrganization(CreateOrganization organization, HttpPostedFileBase LogoImage)
        {
            try
            {
                Organization organi = new Organization();
                if (LogoImage != null)
                {
                    string logoName = WsConstant.randomString() + Path.GetExtension(LogoImage.FileName).ToLower();
                    string path = Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Content/Upload"), logoName);
                    LogoImage.SaveAs(path);
                    organization.LogoUrl = "/Content/Upload/" + logoName;
                }
                
                using (var db = new OrganizationDAL())
                {
                    organi = db.EditOrganization(organization, User.Identity.Name);
                }
                return Redirect("/#/OrganizationDetail/" + organi.OrganizationId);
            }
            catch (Exception)
            {
                return Redirect("/#/Error");
            }
        }
        public ActionResult UpdateUserAvatar(HttpPostedFileBase Image)
        {
            try
            {
               
                string ImageName = WsConstant.randomString() + Path.GetExtension(Image.FileName).ToLower();
                string path = Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Content/Upload"), ImageName);
                Image.SaveAs(path);
                string newName = "/Content/Upload/" + ImageName;
                //Delete Current Image in Upload folder.

                //Update Current Image to UserInformation
                using (var db = new UserDAL())
                {
                    var userId = db.GetUserByUserNameOrEmail(User.Identity.Name).UserID;
                    var userInfo = db.GetUserInformation(userId);
                    userInfo.ProfileImage = newName;
                    using (var context = new Ws_DataContext())
                    {
                        context.User_Information.AddOrUpdate(userInfo);
                        context.SaveChanges();
                    }
                    return Redirect("/#/Profile/" + User.Identity.Name);
                }
            }
            catch (Exception)
            {
                return Redirect("/#/Error");
            }
           
        }
	}
}

WIP/Sources/WingS/WingS/WingS/Controllers/WebApi/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using WingS.DataAccess;
using WingS.DataHelper;
using WingS.Models;
using WingS.Models.DTOs;

namespace WingS.Controllers.WebApi
{
    public class OrganizationController : ApiController
    {
        [HttpGet]
        public IHttpActionResult GetRankOfOrganization(int orgId)
        {
            try
            {
                RankingDTO rankOfOrganization;
                using (var db = new OrganizationDAL())
                {
                    Organization org = db.GetOrganizationById(orgId);

                    WsRanking ranking = new WsRanking();
                    rankOfOrganization = ranking.RankingWithPoint(org.Point);
                }



                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.SUCCESS,
                    Message = "",
                    Type = "",
                    Data = rankOfOrganization
                });
            }
            catch (Exception)
            {

                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.ERROR,
                    Message = "",
                    Type = ""
                });
            }
        }

        [HttpGet]
        public IHttpActionResult GetOrganizationUsingId(int orgId)
        {
            OrganizationBasicInfo currentOrganization = new OrganizationBasicInfo();
            try
            {
                using (var db = new OrganizationDAL())
                {
                    currentOrganization = db.GetFullOrganizationBasicInformation(orgId);
                }

                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.SUCCESS,
                    Message = "",
                    Type = "",
                    Data = currentOrganization
                });
            }
            catch (Exception)
            {

                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.ERROR,
                    Message = "",
                    Type = ""
                });
            }
        }

        
        /// <summary>
        /// Get all organization order by point
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IHttpActionResult GetOrganizationSortByPoint()
        {
            try
            {
                List<OrganizationBasicInfo> allRankedOrganizaation;

                using (var db = new OrganizationDAL())
                {
                    allRankedOrganizaation = db.GetOrganizationOrderByDecendingPoint();
                }

                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.SUCCESS,
                    Message = "",
                    Type = "",
                    Data = allRankedOrganizaation
                });
            }
            catch (Exception)
            {

                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.ERROR,
                    Message = "",
                    Type = ""
                });
            }
        }

        [HttpGet]
        public IHttpActionResult GetTopThreeOrganization()
        {
            var basicOrgList = new List<OrganizationBasicInfo>();
            using (var db = new OrganizationDAL())
            {
                List<Organization> topOrg = db.GetTopThreeOrganizations(3);
                foreach (Organization org in topOrg)
                {
                    basicOrgList.Add(new OrganizationBasicInfo
                    {
                        OrganizationId = org.OrganizationId,
                        OrganizationName = org.OrganizationName,
                        Introduction = org.Introduction,
                        LogoUrl = org.LogoUrl,
                        Phone = org.Phone,
                        Email = org.Email,
                        Address = org.Address,
                        IsActive = org.IsActive,
                        Point = org.Point
                    });
                }

                return Ok(new HTTPMessageDTO {Status = WsConstant.HttpMessageType.SUCCESS, Data = basicOrgList});
            }
        }

        /// <summary>
        /// Get top organization
        /// </summary>
        /// <param name="top"></param>
        /// <returns></returns>
        [HttpGet]
        public IHttpActionResult GetTopOrganization(int top)
        {
            try
            {
                List<OrganizationBasicInfo> orgList;

                using (var db = new OrganizationDAL())
                {
                    orgList = db.GetTopOrganization(top);
                }

                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.SUCCESS,
                    Message = "",
                    Type = "",
                    Data = orgList
                });
            }
            catch (Exception)
            {

                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.ERROR,
                    Message = "",
                    Type = ""
                });
            }
        }

        /// <summary>
        /// Get all organization
        /// </summary>
        /// <param name="top"></param>
        /// <returns></returns>
        [HttpGet]
        public IHttpActionResult GetAllOrganization()
        {
            try
            {
                List<OrganizationBasicInfo> orgList;

                using (var db = new OrganizationDAL())
                {
                    orgList = db.GetAllOrganization();
                }

                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.SUCCESS,
                    Message = "",
                    Type = "",
                    Data = orgList
                });
            }
            catch (Exception)
            {

                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.ERROR,
                    Message = "",
                    Type = ""
                });
            }
        }

        /// <summary>
        /// get all organization which is waiting admin's acception
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IHttpActionResult GetAllOrganizationWaitForAccept()
        {
            try
            {
                List<OrganizationBasicInfo> orgList;

                using (var db = new OrganizationDAL())
                {
                    orgList = db.GetAllOrganizationWaitForAcception();
                }

                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.SUCCESS,
                    Message = "",
                    Type = "",
                    Data = orgList
                });
            }
            catch (Exception)
            {

                return Ok(new HTTPMessageDTO
                {
                    Status = WsConstant.HttpMessageType.ERROR,
                    Message = "",
                    Type = ""
                });
            }
        }

    }
}

WIP/Sources/WingS/WingS/WingS/Views/Organization/_CreateOrganization.cshtml
@model WingS.Models.DTOs.CreateOrganization
<script src="../../Content/scripts/tinymce/js/tinymce/tinymce.min.js" type="text/javascript"></script>
<script type="text/javascript">
    // Initialize your tinyMCE Editor with your preferred options
    tinyMCE.init({
        // General options
        selector: "#organiIntroduction",
        plugins: [
        'advlist autolink lists link image charmap print preview anchor',
         'searchreplace visualblocks code fullscreen',
         'insertdatetime media table contextmenu paste code'
        ],
        toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image| sizeselect | fontselect |  fontsizeselect',
        fontsize_formats: '8pt 10pt 12pt 14pt 18pt 24pt 36pt',
        content_css: '//www.tinymce.com/css/codepen.min.css'
    });
</script>
<div class="divPanel notop nobottom">
</div>

    <div class="contentArea">

        <div class="divPanel notop page-content">

            <div class="breadcrumbs">
                <a href="@Url.Content("/#/Home")">Trang chủ</a> &nbsp;/&nbsp;<a href="#"> Tổ chức</a> &nbsp;/&nbsp; <span>Tạo Tổ chức</span>
            </div>
            @using (Html.BeginForm("CreateOrganization", "Organization", FormMethod.Post, new { @id = "CreateOrganization", @name = "CreateOrganization", enctype = "multipart/form-data" }))
            {
            <div class="row-fluid">
                <div class="span9 offset1">
                    <p>
                        Những mục có dấu <span style="color: red">*</span> không được để trống
                    </p>
                    <div class="alert alert-danger" style="background-color: rgb(240, 240, 240); color: rgb(41, 41, 41);">
                        <div class="row-fluid">
                            <div class="span4" align="center">

                                <h3 style="margin-top: 25px;">
                                    <strong>
                                        Tên Tổ Chức<span style="color: red"> *</span>
                                    </strong>
                                </h3>
                            </div>
                            <div class="span8">
                                <input name="OrganizationName" type="text" style="margin-top: 7px; padding: 10px; border-color: rgb(224, 95, 3); border-radius: 10px; width: 100%;"
                                       ng-model="OrganizationName" ng-minlength="6" ng-maxlength="100" required/>
                                <p>
                                    <span style="color: red" ng-show="CreateOrganization.OrganizationName.$dirty && CreateOrganization.OrganizationName.$invalid">
                                        <span ng-show="CreateOrganization.OrganizationName.$error.required">Tên Tổ chức không được để trống</span>
                                        <span ng-show="CreateOrganization.OrganizationName.$error.minlength">Tên Tổ chức phải trên 6 kí tự</span>
                                        <span ng-show="CreateOrganization.OrganizationName.$error.maxlength">Tên Tổ chức không vượt quá 100 kí tự</span>
                                    </span>
                                </p>
                                <p>
                                    Tên tổ chức bạn nhập vào sẽ giúp mọi người tìm kiếm dễ dàng hơn.
                                </p>

                            </div>
                        </div>
                    </div>
                </div>
                
            </div>

            <div class="row-fluid">
                <div class="span9 offset1">
                    <div class="alert alert-danger" style="background-color: rgb(240, 240, 240); color: rgb(41, 41, 41);">
                        <div class="row-fluid">
                            <div class="span4" align="center">
                                <h3 style="margin-top: 25px;">
                                    <strong>Logo<span style="color: red"> *</span></strong>
                                </h3>
                            </div>
                            <div class="span8">
                                <p>Chọn hình ảnh bạn có</p>
                                <input name="LogoImage" type="file" valid-file-organi ng-model="LogoImage" required>
                                <p style="font-weight: bold;">Chọn file với định dạng JPEG, PNG, GIF, hoặc BMP. Ít nhất với 1024x768 pixels, tỉ lệ 4x3 và không vượt quá 20MB.</p>
                                <p>
                                    <span style="color: red" ng-show="CreateOrganization.LogoImage.$dirty && CreateOrganization.LogoImage.$invalid">
                                        <span ng-show="CreateOrganization.LogoImage.$error.required">Bạn phải chọn ảnh để upload</span>
                                        <span ng-show="CreateOrganization.LogoImage.$error.validFileSize">Kích thước File không thể lớn hơn 20MB</span>
                                        <span ng-show="CreateOrganization.LogoImage.$error.validFileType">Định dạng file không đúng</span>
                                    </span>
                                </p>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span9 offset1">
                    <div class="alert alert-danger" style="background-color: rgb(240, 240, 240); color: rgb(41, 41, 41);">
                        <div class="row-fluid">
                            <div class="span4" align="center">
                                <h3 style="margin-top: 25px;">
                                    <strong>Giới Thiệu<span style="color: red"> *</span></strong>
                                </h3>
                            </div>
                            <div class="span8">
                                <p>Hãy viết phần giới thiệu về tổ chức </p>
                                @*<div id="txtEditor" style="background-color: #fff; height: 300px; margin-bottom: 30px;"></div>*@
                                <textarea id="organiIntroduction" name="Introduction" style="width: 500px; height: 200px;"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span9 offset1">
                    <div class="alert alert-danger" style="background-color: rgb(240, 240, 240); color: rgb(41, 41, 41);">
                        <div class="row-fluid">
                            <div class="span4" align="center">
                                <h3 style="margin-top: 25px;">
                                    <strong>Số điện thoại<span style="color: red"> *</span></strong>
                                </h3>
                            </div>
                            <div class="span8">
                                <input name="Phone" type="number" style="margin-top: 7px; padding: 10px; border-color: rgb(224, 95, 3); border-radius: 10px; width: 100%;"
                                       ng-model="Phone" required />
                                <p>
                                    <span style="color: red" ng-show="CreateOrganization.Phone.$dirty && CreateOrganization.Phone.$invalid">
                                        <span ng-show="CreateOrganization.Phone.$error.required">Số điện thoại không được để trống</span>
                                    </span>
                                </p>
                                <p>
                                    Số điện thoại sẽ hiển thị trên trang của tổ chức, giúp cho việc liên lạc của các thành viên WingS với tổ chức của bạn thuận tiện.
                                </p>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span9 offset1">
                    <div class="alert alert-danger" style="background-color: rgb(240, 240, 240); color: rgb(41, 41, 41);">
                        <div class="row-fluid">
                            <div class="span4" align="center">
                                <h3 style="margin-top: 25px;">
                                    <strong>Email<span style="color: red"> *</span></strong>
                                </h3>
                            </div>
                            <div class="span8">
                                <input name="Email" type="email" style="margin-top: 7px; padding: 10px; border-color: rgb(224, 95, 3); border-radius: 10px; width: 100%;"
                                       ng-model="Email" required />
                                <p>
                                    <span style="color: red" ng-show="CreateOrganization.Email.$dirty && CreateOrganization.Email.$invalid">
                                        <span ng-show="CreateOrganization.Email.$error.required">Địa chỉ Email không được để trống</span>
                                        <span ng-show="CreateOrganization.Email.$error.email">Địa chỉ Email không đúng định dạng</span>
                                    </span>
                                </p>
                                <p>
                                    Nếu tổ chức của bạn có địa chỉ Email cụ thể thì hãy nhập địa chỉ Email vào đây.
                                </p>
                                <!-- <p>Tên tổ chức bạn nhập vào sẽ giúp mọi người tìm kiếm dễ dàng hơn.
                    </p> -->

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span9 offset1">
                    <div class="alert alert-danger" style="background-color: rgb(240, 240, 240); color: rgb(41, 41, 41);">
                        <div class="row-fluid">
                            <div class="span4" align="center">
                                <h3 style="margin-top: 25px;">
                                    <strong>Địa Chỉ</strong>
                                </h3>
                            </div>
                            <div class="span8">
                                <input name="Address" type="text" style="margin-top: 7px; padding: 10px; border-color: rgb(224, 95, 3); border-radius: 10px; width: 100%;" />
                                <p>
                                    Nếu tổ chức của bạn có địa chỉ cụ thể thì hãy nhập địa chỉ vào đây.
                                </p>
                                <!-- <p>Tên tổ chức bạn nhập vào sẽ giúp mọi người tìm kiếm dễ dàng hơn.
                    </p> -->

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span9 offset1" align="right">
                    <button id="createOrgBtn" type="submit" onclick=" return false; " class="btn btn-navbar-highlight btn-large btn-primary" ng-disabled="!CreateOrganization.$dirty || (CreateOrganization.$dirty && CreateOrganization.$invalid)">Tạo Tổ Chức</button>
                </div>
            </div>
            }

        </div>

        </div>
    <div id="footerOuterSeparator"></div>

    @Html.Partial("../Home/_Footer")



<style>
    textarea {
        height: 300px;
    }
</style>
 <script src="../../Content/scripts/default.js" type="text/javascript"></script>
<script>
    $(document).ready(function() {
        $('#title').focus();
    });
</script>
<script type="text/javascript">
    $(function () {
        $('#createOrgBtn').click(function () {
            $('#CreateOrganization').submit();
            alert("Bạn đã yêu cầu tạo tổ chức thành công, vui lòng đợi quyết định từ ban quản trị. Xin cảm ơn!");
        });
    });
</script>

WIP/Sources/WingS/WingS/WingS/Views/Organization/_Organization.cshtml
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<link rel="stylesheet" href="../../Content/scripts/font-awesome-4.6.3/css/font-awesome.min.css">
<script src="../../Content/scripts/default.js" type="text/javascript"></script>
        <div class="divPanel notop nobottom">

        </div>

        <div class="contentArea">

            <div class="divPanel notop page-content">

                <div class="breadcrumbs">
                    <a href="@Url.Content("/#/Home")">Trang chủ</a> &nbsp;/&nbsp; <span>Tổ chức</span>
                </div>

                <div class="row-fluid">
                    <h2>Danh Sách Tổ chức</h2>
                </div>

                <!-- Row 1 -->
                <div class="row">

                    <div class="spanThread addborder" ng-repeat="item in OrgList| limitTo: paginationLimit()">
                        <div class="organization-img">
                            <a href="@Url.Content("/#/OrganizationDetail/{{item.OrganizationId}}")">
                                <img src="{{item.LogoUrl}}" alt="">
                            </a>
                        </div>
                        <div class="contentTop">
                            <div class="organization-name ">
                                <a href="@Url.Content("/#/OrganizationDetail/{{item.OrganizationId}}")">
                                    <h3 class="text-info" style="text-transform: capitalize;">
                                        <strong>{{item.OrganizationName}}</strong>
                                    </h3>
                                </a>
                            </div>
                            <br/>
                            <div class="organization-content " style="overflow: hidden;">
                                <p class="basic-infor">
                                    <i class="fa fa-phone" aria-hidden="true"></i>&nbsp;&nbsp;{{item.Phone}}
                                </p>
                                <p class="basic-infor">
                                    <i class="fa fa-location-arrow" aria-hidden="true"></i>&nbsp;&nbsp;{{item.Address}}
                                </p>                                
                                <p class="basic-infor">
                                    <i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;&nbsp;{{item.Email}}
                                </p>
                            </div>
                            <div class="thread-footer ">

                                <a href="@Url.Content("/#/OrganizationDetail/{{item.OrganizationId}}")">Xem chi tiết &raquo;</a>
                            </div>
                        </div>

                        <br />
                        <br />
                    </div>

                </div>
                <!--/End Portfolio Content Area-->
                <br />
                
                <div align="center">
                    <a class="btn btn-primary" href="#" onclick="return false;" ng-show="hasMoreItemsToShow()" ng-click="showMoreItems()"><i class="icon-refresh icon-spin"></i> Xem thêm...</a>
                </div>
            </div>

            <div id="footerOuterSeparator"></div>

            @Html.Partial("../Home/_Footer")
            <br /><br /><br />
        </div>

WIP/Sources/WingS/WingS/WingS/Views/Organization/_RegistedOrganization.cshtml
<div class="divPanel notop nobottom">

</div>

<div class="contentArea">

    <div class="divPanel notop page-content">

        <div class="breadcrumbs">
            <a href="@Url.Content("/#/Home")">Trang Chủ</a> &nbsp;/&nbsp; <span>Bạn đã đăng kí tổ chức</span>
        </div>

        <div class="row-fluid">
            <!--Edit Main Content Area here-->
            <div class="span12" id="divMain">
                <div style="text-align: center">
                    <p>Bạn đã đăng ký 1 tổ chức rồi!</p>
                    <p>
                        Tổ chức của bạn đang được kiểm duyệt từ ban quản trị, bạn không thể tao thêm tổ chức khác.
                        <a href="@Url.Content("/#/Home")">Quay về trang chủ</a>
                    </p>
                </div>
            </div>
            <!--End Main Content here-->
        </div>
        <br/>
        <br/>
        <div id="footerInnerSeparator"></div>
    </div>
</div>
@Html.Partial("../Home/_Footer")
<br /><br /><br />